#!/bin/bash

name=$(basename "$0")

if ! [ -f "bin/activate" ]; then
  printf "$name: rtfm\n"
  if !  ./script/venv; then
    printf "$name: installation of venv failed\n"
    exit 1
  fi
fi

source bin/activate && python3.10 main.py "$@" && deactivate
